---
- name: Déclenchement des tâches Mautic
  hosts: infomaniak
  gather_facts: no
  tasks:

    - name: Mise à jour des infos geo
      ansible.builtin.shell: php-8.0 /home/clients/bd21b4f6400fa6615dcdc469405ed03b/sites/m.digitalstories.com/bin/console mautic:iplookup:download
      register: result

    - name: Résultat de la mise à jour des infos geo
      debug:
        var: result.stdout
