---
- name: localhost demo
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }}
