- hosts: all
  become: yes
  tasks:
    # Update packages
    - name: update apt packages
      become: true
      apt:
        update: yes
        update_cache: yes

    # Send Discord message when reboot is required
    - name: Send Discord message
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: '{"content": "test"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists
